#ifndef Z_OPUTPUT_H_
#define Z_OUTPUT_H_
/*

[R]andom [I]nsert [C]lear si[Z]e [S]earch [E]rase [B]racket e[X]it: z
Size of BTree: 212
                    zuh 7
                    zrw 100
                zqc 49
                    zow 14
            zos 16
                    zms 88
                zml 81
                    zmb 40
                    zky 55
            zgt 15
                    zfy 70
                    zds 15
                zbq 29
                    zab 69
                yyh 46
                    yya 75
        yug 71
                    ynw 30
                ymo 36
                    yjo 54
                ygi 10
                    xwk 4
            xts 82
                    xnn 66
                xgc 25
                    xct 39
                xca 81
                    xag 92
            wyp 56
                    wtb 75
                    wsu 50
                wrq 67
                    wqo 10
    wny 19
                    wma 80
                    wgp 56
                wat 94
                    vzo 5
                vyn 32
                    vig 72
            vew 25
                    vdh 3
                uuw 24
                    uuf 69
                    usl 92
            urp 57
                    ujg 74
                    uge 80
                uej 29
                    ucv 48
                ube 57
                    uat 42
        ttm 69
                    trw 30
                trp 64
                    tej 7
                tbw 42
                    taq 88
            sut 3
                    spp 5
                slp 21
                    sdd 76
            ryw 12
                    rqx 90
                rpr 66
                    ror 44
                    rmb 97
rkb 70
                    rju 10
                rhw 20
                    rdh 87
                    raq 60
            qst 11
                    qpy 50
                    qnf 56
                qlg 92
                    qee 37
        qdr 92
                    qbe 40
                qan 87
                    qab 69
                psz 18
                    prx 45
                    phw 40
            pfd 28
                    pba 90
                oxt 29
                    oxh 35
    oow 50
                    ooi 25
                olg 90
                    oea 90
                obh 75
                    ntv 85
            nsa 60
                    nqs 60
                nmm 97
                    nfi 79
                myb 27
                    msu 71
        mod 32
                    mnk 12
                mnj 99
                    mek 61
            mai 89
                    lyg 37
                ljv 16
                    lin 3
                    lfo 37
        ldr 98
                    lab 94
                    kyh 50
                kuj 91
                    ksj 99
                    knu 83
            klq 64
                    kkw 43
                kic 68
                    kfz 51
                kfx 57
                    jwe 42
jtx 37
                    jlf 54
                jkj 92
                    jgn 95
                jgj 26
                    jcx 97
            jcm 32
                    iyb 42
                iom 68
                    imf 87
                    ihf 31
            ieu 4
                    iec 13
                idt 95
                    idh 97
                iag 98
                    hze 61
                    hyd 61
        hxr 7
                    hsg 6
                    hrw 97
                hrr 87
                    hpp 22
            him 61
                    hgy 80
                    hbt 1
                gyv 12
                    gyb 56
        gws 47
                    gvj 46
                gva 91
                    guh 15
                    gpw 28
            gmi 13
                    ghm 76
                ggo 29
                    gfv 55
    gbz 46
                    fve 56
                frk 2
                    fqw 34
            fpk 37
                    fof 76
                    fgy 49
                fcn 6
                    fbv 49
                    fac 36
        ewn 55
                    end 17
                ehl 31
                    efa 6
                eau 84
                    ead 92
                    dwu 42
            dvx 53
                    drm 16
                dmq 44
                    dke 18
                    dic 52
            dgv 51
                    det 56
                ddo 21
                    dci 7
    dbi 80
                    cve 10
                ctj 91
                    cnk 53
            cds 66
                    cdk 41
                cca 38
                    bnx 34
            bjx 60
                    biv 39
                bil 87
                    bic 31
                bgq 32
                    bbz 72
        bby 5
                    bbj 50
                bat 32
                    awh 16
                    avu 25
            avs 34
                    ato 67
                ate 87
                    aqc 71
            ald 97
                    ala 68
                aji 14
                    adu 60
                    acs 44


=========================
[R]andom [I]nsert [C]lear si[Z]e [S]earch [E]rase [B]racket e[X]it: i steven 50
? -- Inserting steven,50
Map : item: steven,50
                    zuh 7
                    zrw 100
                zqc 49
                    zow 14
            zos 16
                    zms 88
                zml 81
                    zmb 40
                    zky 55
            zgt 15
                    zfy 70
                    zds 15
                zbq 29
                    zab 69
                yyh 46
                    yya 75
        yug 71
                    ynw 30
                ymo 36
                    yjo 54
                ygi 10
                    xwk 4
            xts 82
                    xnn 66
                xgc 25
                    xct 39
                xca 81
                    xag 92
            wyp 56
                    wtb 75
                    wsu 50
                wrq 67
                    wqo 10
    wny 19
                    wma 80
                    wgp 56
                wat 94
                    vzo 5
                vyn 32
                    vig 72
            vew 25
                    vdh 3
                uuw 24
                    uuf 69
                    usl 92
            urp 57
                    ujg 74
                    uge 80
                uej 29
                    ucv 48
                ube 57
                    uat 42
        ttm 69
                    trw 30
                trp 64
                    tej 7
                tbw 42
                    taq 88
            sut 3
                    steven 50
                    spp 5
                slp 21
                    sdd 76
            ryw 12
                    rqx 90
                rpr 66
                    ror 44
                    rmb 97
rkb 70
                    rju 10
                rhw 20
                    rdh 87
                    raq 60
            qst 11
                    qpy 50
                    qnf 56
                qlg 92
                    qee 37
        qdr 92
                    qbe 40
                qan 87
                    qab 69
                psz 18
                    prx 45
                    phw 40
            pfd 28
                    pba 90
                oxt 29
                    oxh 35
    oow 50
                    ooi 25
                olg 90
                    oea 90
                obh 75
                    ntv 85
            nsa 60
                    nqs 60
                nmm 97
                    nfi 79
                myb 27
                    msu 71
        mod 32
                    mnk 12
                mnj 99
                    mek 61
            mai 89
                    lyg 37
                ljv 16
                    lin 3
                    lfo 37
        ldr 98
                    lab 94
                    kyh 50
                kuj 91
                    ksj 99
                    knu 83
            klq 64
                    kkw 43
                kic 68
                    kfz 51
                kfx 57
                    jwe 42
jtx 37
                    jlf 54
                jkj 92
                    jgn 95
                jgj 26
                    jcx 97
            jcm 32
                    iyb 42
                iom 68
                    imf 87
                    ihf 31
            ieu 4
                    iec 13
                idt 95
                    idh 97
                iag 98
                    hze 61
                    hyd 61
        hxr 7
                    hsg 6
                    hrw 97
                hrr 87
                    hpp 22
            him 61
                    hgy 80
                    hbt 1
                gyv 12
                    gyb 56
        gws 47
                    gvj 46
                gva 91
                    guh 15
                    gpw 28
            gmi 13
                    ghm 76
                ggo 29
                    gfv 55
    gbz 46
                    fve 56
                frk 2
                    fqw 34
            fpk 37
                    fof 76
                    fgy 49
                fcn 6
                    fbv 49
                    fac 36
        ewn 55
                    end 17
                ehl 31
                    efa 6
                eau 84
                    ead 92
                    dwu 42
            dvx 53
                    drm 16
                dmq 44
                    dke 18
                    dic 52
            dgv 51
                    det 56
                ddo 21
                    dci 7
    dbi 80
                    cve 10
                ctj 91
                    cnk 53
            cds 66
                    cdk 41
                cca 38
                    bnx 34
            bjx 60
                    biv 39
                bil 87
                    bic 31
                bgq 32
                    bbz 72
        bby 5
                    bbj 50
                bat 32
                    awh 16
                    avu 25
            avs 34
                    ato 67
                ate 87
                    aqc 71
            ald 97
                    ala 68
                aji 14
                    adu 60
                    acs 44


=========================
[R]andom [I]nsert [C]lear si[Z]e [S]earch [E]rase [B]racket e[X]it: b steven
? map[steven] = 50
                    zuh 7
                    zrw 100
                zqc 49
                    zow 14
            zos 16
                    zms 88
                zml 81
                    zmb 40
                    zky 55
            zgt 15
                    zfy 70
                    zds 15
                zbq 29
                    zab 69
                yyh 46
                    yya 75
        yug 71
                    ynw 30
                ymo 36
                    yjo 54
                ygi 10
                    xwk 4
            xts 82
                    xnn 66
                xgc 25
                    xct 39
                xca 81
                    xag 92
            wyp 56
                    wtb 75
                    wsu 50
                wrq 67
                    wqo 10
    wny 19
                    wma 80
                    wgp 56
                wat 94
                    vzo 5
                vyn 32
                    vig 72
            vew 25
                    vdh 3
                uuw 24
                    uuf 69
                    usl 92
            urp 57
                    ujg 74
                    uge 80
                uej 29
                    ucv 48
                ube 57
                    uat 42
        ttm 69
                    trw 30
                trp 64
                    tej 7
                tbw 42
                    taq 88
            sut 3
                    steven 50
                    spp 5
                slp 21
                    sdd 76
            ryw 12
                    rqx 90
                rpr 66
                    ror 44
                    rmb 97
rkb 70
                    rju 10
                rhw 20
                    rdh 87
                    raq 60
            qst 11
                    qpy 50
                    qnf 56
                qlg 92
                    qee 37
        qdr 92
                    qbe 40
                qan 87
                    qab 69
                psz 18
                    prx 45
                    phw 40
            pfd 28
                    pba 90
                oxt 29
                    oxh 35
    oow 50
                    ooi 25
                olg 90
                    oea 90
                obh 75
                    ntv 85
            nsa 60
                    nqs 60
                nmm 97
                    nfi 79
                myb 27
                    msu 71
        mod 32
                    mnk 12
                mnj 99
                    mek 61
            mai 89
                    lyg 37
                ljv 16
                    lin 3
                    lfo 37
        ldr 98
                    lab 94
                    kyh 50
                kuj 91
                    ksj 99
                    knu 83
            klq 64
                    kkw 43
                kic 68
                    kfz 51
                kfx 57
                    jwe 42
jtx 37
                    jlf 54
                jkj 92
                    jgn 95
                jgj 26
                    jcx 97
            jcm 32
                    iyb 42
                iom 68
                    imf 87
                    ihf 31
            ieu 4
                    iec 13
                idt 95
                    idh 97
                iag 98
                    hze 61
                    hyd 61
        hxr 7
                    hsg 6
                    hrw 97
                hrr 87
                    hpp 22
            him 61
                    hgy 80
                    hbt 1
                gyv 12
                    gyb 56
        gws 47
                    gvj 46
                gva 91
                    guh 15
                    gpw 28
            gmi 13
                    ghm 76
                ggo 29
                    gfv 55
    gbz 46
                    fve 56
                frk 2
                    fqw 34
            fpk 37
                    fof 76
                    fgy 49
                fcn 6
                    fbv 49
                    fac 36
        ewn 55
                    end 17
                ehl 31
                    efa 6
                eau 84
                    ead 92
                    dwu 42
            dvx 53
                    drm 16
                dmq 44
                    dke 18
                    dic 52
            dgv 51
                    det 56
                ddo 21
                    dci 7
    dbi 80
                    cve 10
                ctj 91
                    cnk 53
            cds 66
                    cdk 41
                cca 38
                    bnx 34
            bjx 60
                    biv 39
                bil 87
                    bic 31
                bgq 32
                    bbz 72
        bby 5
                    bbj 50
                bat 32
                    awh 16
                    avu 25
            avs 34
                    ato 67
                ate 87
                    aqc 71
            ald 97
                    ala 68
                aji 14
                    adu 60
                    acs 44


=========================
[R]andom [I]nsert [C]lear si[Z]e [S]earch [E]rase [B]racket e[X]it: e steven
? -- Erasing steven
Map : item: steven
                    zuh 7
                    zrw 100
                zqc 49
                    zow 14
            zos 16
                    zms 88
                zml 81
                    zmb 40
                    zky 55
            zgt 15
                    zfy 70
                    zds 15
                zbq 29
                    zab 69
                yyh 46
                    yya 75
        yug 71
                    ynw 30
                ymo 36
                    yjo 54
                ygi 10
                    xwk 4
            xts 82
                    xnn 66
                xgc 25
                    xct 39
                xca 81
                    xag 92
            wyp 56
                    wtb 75
                    wsu 50
                wrq 67
                    wqo 10
    wny 19
                    wma 80
                    wgp 56
                wat 94
                    vzo 5
                vyn 32
                    vig 72
            vew 25
                    vdh 3
                uuw 24
                    uuf 69
                    usl 92
            urp 57
                    ujg 74
                    uge 80
                uej 29
                    ucv 48
                ube 57
                    uat 42
        ttm 69
                    trw 30
                trp 64
                    tej 7
                tbw 42
                    taq 88
            sut 3
                    spp 5
                slp 21
                    sdd 76
            ryw 12
                    rqx 90
                rpr 66
                    ror 44
                    rmb 97
rkb 70
                    rju 10
                rhw 20
                    rdh 87
                    raq 60
            qst 11
                    qpy 50
                    qnf 56
                qlg 92
                    qee 37
        qdr 92
                    qbe 40
                qan 87
                    qab 69
                psz 18
                    prx 45
                    phw 40
            pfd 28
                    pba 90
                oxt 29
                    oxh 35
    oow 50
                    ooi 25
                olg 90
                    oea 90
                obh 75
                    ntv 85
            nsa 60
                    nqs 60
                nmm 97
                    nfi 79
                myb 27
                    msu 71
        mod 32
                    mnk 12
                mnj 99
                    mek 61
            mai 89
                    lyg 37
                ljv 16
                    lin 3
                    lfo 37
        ldr 98
                    lab 94
                    kyh 50
                kuj 91
                    ksj 99
                    knu 83
            klq 64
                    kkw 43
                kic 68
                    kfz 51
                kfx 57
                    jwe 42
jtx 37
                    jlf 54
                jkj 92
                    jgn 95
                jgj 26
                    jcx 97
            jcm 32
                    iyb 42
                iom 68
                    imf 87
                    ihf 31
            ieu 4
                    iec 13
                idt 95
                    idh 97
                iag 98
                    hze 61
                    hyd 61
        hxr 7
                    hsg 6
                    hrw 97
                hrr 87
                    hpp 22
            him 61
                    hgy 80
                    hbt 1
                gyv 12
                    gyb 56
        gws 47
                    gvj 46
                gva 91
                    guh 15
                    gpw 28
            gmi 13
                    ghm 76
                ggo 29
                    gfv 55
    gbz 46
                    fve 56
                frk 2
                    fqw 34
            fpk 37
                    fof 76
                    fgy 49
                fcn 6
                    fbv 49
                    fac 36
        ewn 55
                    end 17
                ehl 31
                    efa 6
                eau 84
                    ead 92
                    dwu 42
            dvx 53
                    drm 16
                dmq 44
                    dke 18
                    dic 52
            dgv 51
                    det 56
                ddo 21
                    dci 7
    dbi 80
                    cve 10
                ctj 91
                    cnk 53
            cds 66
                    cdk 41
                cca 38
                    bnx 34
            bjx 60
                    biv 39
                bil 87
                    bic 31
                bgq 32
                    bbz 72
        bby 5
                    bbj 50
                bat 32
                    awh 16
                    avu 25
            avs 34
                    ato 67
                ate 87
                    aqc 71
            ald 97
                    ala 68
                aji 14
                    adu 60
                    acs 44


=========================
[R]andom [I]nsert [C]lear si[Z]e [S]earch [E]rase [B]racket e[X]it: b steven
? map[steven] = 0
                    zuh 7
                    zrw 100
                zqc 49
                    zow 14
            zos 16
                    zms 88
                zml 81
                    zmb 40
                    zky 55
            zgt 15
                    zfy 70
                    zds 15
                zbq 29
                    zab 69
                yyh 46
                    yya 75
        yug 71
                    ynw 30
                ymo 36
                    yjo 54
                ygi 10
                    xwk 4
            xts 82
                    xnn 66
                xgc 25
                    xct 39
                xca 81
                    xag 92
            wyp 56
                    wtb 75
                    wsu 50
                wrq 67
                    wqo 10
    wny 19
                    wma 80
                    wgp 56
                wat 94
                    vzo 5
                vyn 32
                    vig 72
            vew 25
                    vdh 3
                uuw 24
                    uuf 69
                    usl 92
            urp 57
                    ujg 74
                    uge 80
                uej 29
                    ucv 48
                ube 57
                    uat 42
        ttm 69
                    trw 30
                trp 64
                    tej 7
                tbw 42
                    taq 88
            sut 3
                    steven 0
                    spp 5
                slp 21
                    sdd 76
            ryw 12
                    rqx 90
                rpr 66
                    ror 44
                    rmb 97
rkb 70
                    rju 10
                rhw 20
                    rdh 87
                    raq 60
            qst 11
                    qpy 50
                    qnf 56
                qlg 92
                    qee 37
        qdr 92
                    qbe 40
                qan 87
                    qab 69
                psz 18
                    prx 45
                    phw 40
            pfd 28
                    pba 90
                oxt 29
                    oxh 35
    oow 50
                    ooi 25
                olg 90
                    oea 90
                obh 75
                    ntv 85
            nsa 60
                    nqs 60
                nmm 97
                    nfi 79
                myb 27
                    msu 71
        mod 32
                    mnk 12
                mnj 99
                    mek 61
            mai 89
                    lyg 37
                ljv 16
                    lin 3
                    lfo 37
        ldr 98
                    lab 94
                    kyh 50
                kuj 91
                    ksj 99
                    knu 83
            klq 64
                    kkw 43
                kic 68
                    kfz 51
                kfx 57
                    jwe 42
jtx 37
                    jlf 54
                jkj 92
                    jgn 95
                jgj 26
                    jcx 97
            jcm 32
                    iyb 42
                iom 68
                    imf 87
                    ihf 31
            ieu 4
                    iec 13
                idt 95
                    idh 97
                iag 98
                    hze 61
                    hyd 61
        hxr 7
                    hsg 6
                    hrw 97
                hrr 87
                    hpp 22
            him 61
                    hgy 80
                    hbt 1
                gyv 12
                    gyb 56
        gws 47
                    gvj 46
                gva 91
                    guh 15
                    gpw 28
            gmi 13
                    ghm 76
                ggo 29
                    gfv 55
    gbz 46
                    fve 56
                frk 2
                    fqw 34
            fpk 37
                    fof 76
                    fgy 49
                fcn 6
                    fbv 49
                    fac 36
        ewn 55
                    end 17
                ehl 31
                    efa 6
                eau 84
                    ead 92
                    dwu 42
            dvx 53
                    drm 16
                dmq 44
                    dke 18
                    dic 52
            dgv 51
                    det 56
                ddo 21
                    dci 7
    dbi 80
                    cve 10
                ctj 91
                    cnk 53
            cds 66
                    cdk 41
                cca 38
                    bnx 34
            bjx 60
                    biv 39
                bil 87
                    bic 31
                bgq 32
                    bbz 72
        bby 5
                    bbj 50
                bat 32
                    awh 16
                    avu 25
            avs 34
                    ato 67
                ate 87
                    aqc 71
            ald 97
                    ala 68
                aji 14
                    adu 60
                    acs 44


=========================
[R]andom [I]nsert [C]lear si[Z]e [S]earch [E]rase [B]racket e[X]it: c


=========================
[R]andom [I]nsert [C]lear si[Z]e [S]earch [E]rase [B]racket e[X]it: x


=========================

C:\Users\Steven_dev\Desktop\CS_Stuff\Map-Class\MapClass\Debug\MapClass.exe (process 16952) exited with code 0.
Press any key to close this window . . .
*/
#endif // !Z_OPUTPUT_H_
